FROM node12
MAINTAINER Giles Gamon "giles@lsiarchi.consulting"

RUN yum install -y zip unzip git curl tar wget make gzip zip zlib-devel gcc openssl-devel bzip2-devel libffi-devel file hostname

RUN yum install -y java-11-amazon-corretto

ENV JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto.x86_64
ENV PATH=$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
