FROM openjdk_11
MAINTAINER Giles Gamon "giles@lsiarchi.consulting"

RUN yum install -y openssl maven

ADD . /root/ecs-camel-sqs
RUN cp /root/ecs-camel-sqs/docker/safe/caCert.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust
RUN cd /root/ecs-camel-sqs/docker/safe && source ./secrets && cd /root/ecs-camel-sqs && ./parse_params && mvn clean install && cp target/*jar /tmp && cp src/main/resources/server-chain.jks /tmp
RUN rm -rf /root/ecs-camel-sqs/docker/safe